default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: <%= ENV['SIGNUP_DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: signup_development

test:
  <<: *default
  database: signup_test

production:
  <<: *default
  database: signup_production
